-- Least-privilege role for dbt (run once as ACCOUNTADMIN).
--
-- dbt previously connected as ACCOUNTADMIN. HYDEN_DBT_ROLE can only:
--   * run queries on the HYDEN_WH warehouse
--   * read the raw pipeline tables in HYDEN_SEQ.PIPELINE (never write them)
--   * own and rebuild the schemas dbt manages: ANALYTICS_STAGING, ANALYTICS_MARTS
-- It has no access to other databases and no account-level privileges.
-- The role is granted to SYSADMIN, so admins still see everything it owns.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS HYDEN_DBT_ROLE
  COMMENT = 'dbt for HYDEN_SEQ: read PIPELINE, build ANALYTICS_* schemas';

-- Compute
GRANT USAGE ON WAREHOUSE HYDEN_WH TO ROLE HYDEN_DBT_ROLE;

-- Database; CREATE SCHEMA lets dbt add a schema for a new model folder
GRANT USAGE ON DATABASE HYDEN_SEQ TO ROLE HYDEN_DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE HYDEN_SEQ TO ROLE HYDEN_DBT_ROLE;

-- Sources: read-only, including tables and views created later
GRANT USAGE ON SCHEMA HYDEN_SEQ.PIPELINE TO ROLE HYDEN_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HYDEN_SEQ.PIPELINE TO ROLE HYDEN_DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA HYDEN_SEQ.PIPELINE TO ROLE HYDEN_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HYDEN_SEQ.PIPELINE TO ROLE HYDEN_DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HYDEN_SEQ.PIPELINE TO ROLE HYDEN_DBT_ROLE;

-- dbt-managed schemas: the role owns them and everything in them,
-- so `dbt build` can create, replace and drop its own models
GRANT OWNERSHIP ON SCHEMA HYDEN_SEQ.ANALYTICS_STAGING TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA HYDEN_SEQ.ANALYTICS_STAGING TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA HYDEN_SEQ.ANALYTICS_STAGING TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA HYDEN_SEQ.ANALYTICS_MARTS TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA HYDEN_SEQ.ANALYTICS_MARTS TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA HYDEN_SEQ.ANALYTICS_MARTS TO ROLE HYDEN_DBT_ROLE COPY CURRENT GRANTS;

-- Role hierarchy: SYSADMIN (and therefore ACCOUNTADMIN) inherits this role
GRANT ROLE HYDEN_DBT_ROLE TO ROLE SYSADMIN;
GRANT ROLE HYDEN_DBT_ROLE TO USER CLAUSENAR;
